


<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset='utf-8'/>

		<title>
			<?php 
				echo $siteName . " - ".$pageTitle; ?>

		</title>
		<link rel="stylesheet" type="text/css"
			href="<?php echo WEB_ROOT?>css/bootstrap.min.css"/>
		<link rel="stylesheet" type="text/css"
			href="<?php echo WEB_ROOT?>css/layout/blog.css"/>
	</head>
	<body>
	<?php
		echo $viewContent;
	?>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="<?php echo WEB_ROOT?>js/bootstrap.min.js"></script>

	</body>
</html>


